### ISSUE TITLE
DbContext transaction mechanism possibly swallowing exception?

### ISSUE THREAD

**Issue by mderriey** [jbogard/ContosoUniversityCore#1]
Hi Jimmy,

Looking at [this code](https://github.com/jbogard/ContosoUniversityCore/blob/7d788093902f7c05e0dc94fc1e95122f28453edb/src/ContosoUniversityCore/Infrastructure/SchoolContext.cs#L47), I can't help but think it could swallow an exception. That `catch` statement calls `RollbackTransaction`, but doesn't `throw`.

Since the [associated MVC filter](https://github.com/jbogard/ContosoUniversityCore/blob/7d788093902f7c05e0dc94fc1e95122f28453edb/src/ContosoUniversityCore/Infrastructure/DbContextTransactionFilter.cs#L16) rolls back if an exception is caught and rethrows, shouldn't `CommitTransactionAsync` just take care of committing the transaction and disposing of it if all works well, and let the MVC filter handle the exception scenario? Or at least rethrow the exception (that's what the [non-Core version](https://github.com/jbogard/ContosoUniversity/blob/a8d396f3df0f2db85ad8fc92125a1334cee015aa/src/ContosoUniversity/DAL/SchoolContext.cs#L61) does.

Cheers

**Comment by jbogard** [comment]
Yep, that's a bug!

**Comment by mderriey** [comment]
Sorry I didn't create a PR, I just wasn't sure this was an issue and I thought I could have missed something.
Which, in hindsight, is stupid because the PR would have just not been merged.
A lesson for next time, I guess.

Thanks!

**Comment by jbogard** [comment]
It took me an hour to debug this so lol
