### ISSUE TITLE
Question: How are the validators called?

### ISSUE THREAD

**Issue by nojaf** [jbogard/ContosoUniversityCore#12]
I can't put my finger on it but what part of the code will actually trigger the Validator class in [ContosoUniversityCore/src/ContosoUniversityCore/Features/Student/Create.cs](https://github.com/jbogard/ContosoUniversityCore/blob/master/src/ContosoUniversityCore/Features/Student/Create.cs)?

I'm guessing you override some ModelStateValidator somewhere but I can't seem to tell where.

**Comment by jbogard** [comment]
Not magic! https://github.com/jbogard/ContosoUniversityCore/blob/master/src/ContosoUniversityCore/Startup.cs#L40

Everything is set up in the Startup class (which I quite like for how explicit it is).

You'll see tho a lot of library authors are building extensions to make adding it all one liners.

**Comment by nojaf** [comment]
So [this](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs#L23) will make sure that the matching AbstractValidator<T> is found and executed for any incoming T model?

**Comment by jbogard** [comment]
Yep!
