### ISSUE TITLE
Course edit database constraint error

### ISSUE THREAD

**Issue by bobgodfrey** [jbogard/ContosoUniversityCore#13]
Jimmy, 

First off I love your work, really interesting.  I have a question and a issue.   

The questions - where to you generally put core business validation logic.   I am talking about a situation where the model state is valid, but the pending change violates some high-level business rule.   (ex an instructor can only be assigned to two classes at a time).

The issue I found is an error if you modify a course and remove the selected department (set the drop down to nothing).   When you save course, it passes model validation but it throws and error/ violates a database constraint given the null department .  The end result in the sample application is the user is stuck on the course edit page with no error feedback.   I know the simple answer would be to validate the model to make sure it has a valid department.   What I wanted was some type of centralized valuation.   I am assuming that I could add an additional filter and return json errors if appropriate?

Let me know your thoughts

**Comment by jbogard** [comment]
I actually just blogged about this! What do you think?
