### ISSUE TITLE
Question: Why is the domain in a different folder / namespace? 

### ISSUE THREAD

**Issue by christianarg** [jbogard/ContosoUniversityCore#17]
Shouldn't be the domain model / entities / whateveryoucallthem be distributed among the feature modules / slices / whateveryoucallthem? 

For example: ContosoUniversityCore.Domain.Course

shouldn't be located in 

ContosoUniversityCore.Features.Courses.Course

/* 
I've modified the Feature.Course namespace to Feature.Courses in plural. Maybe that's the reason you wouldn't do this? In our company we learned to "pluralize" modules / namespaces to avoid conflict with domain objects.
*/

Anyway, if my suggestion is wrong, could you provide a reasoning for having the Domain in a different folder / namespace / (module?)

**Comment by jbogard** [comment]
Domain is shared across all features, is why. And yes, the plural name makes more sense in any case :)

**Comment by christianarg** [comment]
I see. Last question: If your domain was somewhat bigger would you organize Domain classes in modules / namespaces?  Ex:

Features.Customer // UI, js, Controllers, Handlers
Features.Shipping // UI, js, Controllers, Handlers
Features.Billing  // UI, js, Controllers, Handlers

Domain.Customer
Domain.Shipping
Domain.Billing 

Or you don't see value in that? Just curious

(I'm implying we are not dividing this modules in microservices, just one well modularized monolithic app)

Thanks for your time.

**Comment by jbogard** [comment]
I think if I were doing a purely module based approach, this would make
sense. For me though, feature folders more or less correspond to
controllers, so the models don't allllllways line up.
