### ISSUE TITLE
Question: Why not use EF migrations?

### ISSUE THREAD

**Issue by egil** [jbogard/ContosoUniversityCore#2]
Hi Jimmy,

I was reading through the code in this repo and started wondering why you do not use EF migrations. Can you elaborate on that decision?
 
Are there any pitfalls that makes it preferable just to have a hand-crafted SchemaAndData.sql?

Best, Egil

**Comment by jbogard** [comment]
The codebase doesn't use any migrations because we don't need to migrate anything, just schema and data. I thought a single SQL script would be easier than restoring a backup file. Maybe not!

We don't use EF or any code-base migrations, only SQL-based in any case, Roundhouse for example.

**Comment by egil** [comment]
Interesting, I did not know Roundhouse. To me it seems EF migrations do have some neat benefits, but I have yet to use it in a real production system. Do you mind sharing your thoughts on EF/other code-based database migration solutions vs. SQL-based ones?

**Comment by jbogard** [comment]
Well, with SQL, I have complete control of what's going to be executed
against the DB. If something goes wrong, I have the exact SQL that
executed. And RoundHouse supports a large number of scenarios (different
environments, scripts for views/sprocs etc) that make it a comprehensive
solution.

**Comment by NagarajanGitHub** [comment]
Where can i find the "SchemaAndData.sql" file?

**Comment by jbogard** [comment]
It's at the root of the project.
