### ISSUE TITLE
Question: Why is the project targetting 4.6.1

### ISSUE THREAD

**Issue by kalimist123** [jbogard/ContosoUniversityCore#20]
I tried to build this project from scratch starting with a .Net Core 2.0 project type. I keep getting System.TypeInitializationException: 'The type initializer for 'System.Data.Entity.Internal.AppConfig' threw an exception.' FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
...in the schoolcontext on start.

When I compared my own project with this one, I see that this project is targeting .Net 4.6.1. 
Can you explain why this targetting 4.6.1 and not .Net Core?

**Comment by jbogard** [comment]
I have a separate project for ContosoUniversity on .NET Core. That is not this one, check out the "ContosoUniversityDotNetCore" project.

This one is for ASP.NET Core on full .NET framework (that's why I'm using EF6 for example).
