### ISSUE TITLE
One or more packages are incompatible with .NETFramework, Version=v4.6.1

### ISSUE THREAD

**Issue by beriniwlew** [jbogard/ContosoUniversityCore#23]
I'm getting an error "One or more packages are incompatible with .NETFramework, Version=v4.6.1" when attempting to build the solution.

New to .Net Core

**Comment by beriniwlew** [comment]
Fixed it by updating Visual Studio 2017

**Comment by kiquenet** [comment]
Visual Studio 2017 compiles NETFramework, Version=v4.6.1 and Core libraries ?
