### ISSUE TITLE
Build.ps1 tools

### ISSUE THREAD

**Issue by kiquenet** [jbogard/ContosoUniversityCore#24]
What is rh.exe and Octo.exe? free tools ?

dotnet command:

exec { & dotnet restore }
exec { & dotnet build -c Release --version-suffix=$buildSuffix }

**Comment by jbogard** [comment]
rh.exe is RoundHouse, a tool for SQL migrations. octo.exe is from Octopus Deploy, and is used to create releases. These two tools are used for a continuous integration/delivery pipeline.
