### ISSUE TITLE
Bad Idea: Binding to Entities. Or is it?

### ISSUE THREAD

**Issue by cocowalla** [jbogard/ContosoUniversityCore#29]
I came your [slide deck](https://github.com/jbogard/presentations/blob/master/ORMs/Orms.pptx) on ORMs, and have a question on slide 45 "Bad Idea: Binding to Entities" - doesn't `EntityModelBinder` in your Contono Github repos go against this?

**Comment by jbogard** [comment]
The talk example is about binding request variables to entities. The `EntityModelBinder` is about loading an entity via ID in the request.

**Comment by cocowalla** [comment]
My bad
