### ISSUE TITLE
System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by SrikanthGollapudi** [jbogard/ContosoUniversityCore#37]
Project compiled and home page loads fine. But when I click either Student, Contacts, Courses and Instructor tabs, I get following error

System.MissingMethodException: Method not found: 'Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.ModelBindingMessageProvider Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.BindingMetadata.get_ModelBindingMessageProvider()'.

I tried upgrading AspCore.MVC to 2.2.0, but still doesn't help. 
Also, tried clearing nuget cache and rebuilding doesn't help

**Note: Only Department tab works
![image](https://user-images.githubusercontent.com/5810217/108004502-e6121400-6faa-11eb-9332-afeb80649fc9.png)

**Comment by jbogard** [comment]
I don't really maintain this repo, I've moved over to the DotNetCorePages one.
