### ISSUE TITLE
Purpose of RedirectToActionJson

### ISSUE THREAD

**Issue by grokky1** [jbogard/ContosoUniversityCore#9]
Anyone know what is the purpose of [RedirectToActionJson](http://github.com/jbogard/ContosoUniversityCore/blob/master/src/ContosoUniversityCore/Features/ControllerExtensions.cs)? Used [here for example](http://github.com/jbogard/ContosoUniversityCore/blob/master/src/ContosoUniversityCore/Features/Student/StudentController.cs#L74).

It's used in many actions.

Why not just redirect to the action directly - the request was made normally, so why respond with JSON?

**Comment by DejanMilicic** [comment]
As you can see [here](https://github.com/jbogard/ContosoUniversityCore/blob/4a5b220fd6f7e0428bdf1b1974ecc91af645a808/src/ContosoUniversityCore/wwwroot/js/site.js#L62), by default all forms (unless they are marked with "no-ajax" class) are submitted via ajax.
